name: ppp
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - notebook
  - mkl
  - graphviz
  - seaborn
  - pydot
  - matplotlib
  - arviz[version='>=0.7']
  - pymc3
  - scipy
  - pandas
  - theano
  - numpy
  - mkl-service
  - watermark
  - jupyter
